#!/bin/bash

# Fallback if env vars not set (prevents sourcing errors in automation)
DOMAIN_FQDN="${DOMAIN_FQDN:-example.local}"
DOMAIN_NETBIOS="${DOMAIN_NETBIOS:-EXAMPLE}"

# Derive case variants (Bash 4+ parameter expansion)
DOMAIN_FQDN_LCASE="${DOMAIN_FQDN,,}"
DOMAIN_FQDN_UCASE="${DOMAIN_FQDN^^}"
DOMAIN_NETBIOS_UPPER="${DOMAIN_NETBIOS^^}"  # Ensure NetBIOS is uppercase

# Config paths
CONFIG_DIR="/etc/samba/config"
CONFIG_FILE="$CONFIG_DIR/smb.conf"
DEFAULT_CONFIG_FILE="/etc/samba/smb.conf"
USERMAP_FILE="$CONFIG_DIR/user.map"

# Kerberos paths
KERBEROS_CONFIG_FILE="/etc/krb5.conf"
KERBEROS_PRIVATE_FILE="/var/lib/samba/private/krb5.conf"  # Generated by provision

# Export all for child scripts (e.g., samba-provision.sh)
export DOMAIN_FQDN DOMAIN_FQDN_LCASE DOMAIN_FQDN_UCASE DOMAIN_NETBIOS DOMAIN_NETBIOS_UPPER
export CONFIG_DIR CONFIG_FILE DEFAULT_CONFIG_FILE USERMAP_FILE
export KERBEROS_CONFIG_FILE KERBEROS_PRIVATE_FILE

# Optional: Echo for debug logs (remove after testing)
# echo "vars.sh loaded: DOMAIN_FQDN=${DOMAIN_FQDN}, UCASE=${DOMAIN_FQDN_UCASE}, NETBIOS=${DOMAIN_NETBIOS}"
